version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
    - echo Installing dependencies...
    - go mod download

  pre_build:
    commands:
    - echo Running tests...
    - go test ./... -v

  build:
    commands:
    - echo Building the application...
    - make build
    - echo $DATABASE_DEBUG
    - echo $DATABASE_MIGRATE
    - echo $BIRTHDAY_TITLE
    - echo $BIRTHDAY_TEXT
    - echo $NOTIFY_URL
    - echo $NOTIFY_TOKEN
    - echo Deploying the application...
    - make deploy --parameter-overrides DATABASE_DEBUG=$DATABASE_DEBUG DATABASE_MIGRATE=$DATABASE_MIGRATE BIRTHDAY_TITLE=$BIRTHDAY_TITLE BIRTHDAY_TEXT=$BIRTHDAY_TEXT NOTIFY_URL=$NOTIFY_URL NOTIFY_TOKEN=$NOTIFY_TOKEN

artifacts:
  files:
  - template.yaml
  - bin/**/*
  - .aws-sam/**/*
  discard-paths: no

cache:
  paths:
  - /go/pkg/mod/**/*
