version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
    - echo Installing dependencies...
    - go mod download

  pre_build:
    commands:
    - echo Running tests...
    - go test ./... -v

  build:
    commands:
    - echo Building the application...
    - make build
    - echo Deploying the application...
    - |
      sam deploy --no-confirm-changeset \
        --parameter-overrides \
        Stage=${STAGE:-dev} \
        DatabaseDebug=${DATABASE_DEBUG:-false} \
        NativeLoggerTrace=${NATIVE_LOGGER_TRACE:-0} \
        DatabaseUser=${DATABASE_USER:-root} \
        DatabasePassword=${DATABASE_PASSWORD:-root} \
        DatabaseHost=${DATABASE_HOST:-localhost} \
        DatabasePort=${DATABASE_PORT:-3306} \
        DatabaseName=${DATABASE_NAME:-axul_contact} \
        DatabaseMigrate=${DATABASE_MIGRATE:-true} \
        BirthdayTitle="${BIRTHDAY_TITLE:-'Happy Birthday %s %s!'}" \
        BirthdayText="${BIRTHDAY_TEXT:-'Today is %s %s\'s birthday!'}" \
        NotifyUrl=${NOTIFY_URL:-http://localhost:8080} \
        NotifyToken=${NOTIFY_TOKEN:-default-token}

artifacts:
  files:
  - template.yaml
  - bin/**/*
  - .aws-sam/**/*
  discard-paths: no

cache:
  paths:
  - /go/pkg/mod/**/*
