version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
    - echo Installing dependencies...
    - go mod download

  pre_build:
    commands:
    - echo Running tests...
    - go test ./... -v

  build:
    commands:
    - echo Building the application...
    - make build
    - echo Deploying the application...
    - |
      sam deploy --no-confirm-changeset \
        --parameter-overrides \
        "STAGE=${STAGE} \
        DATABASE_DEBUG=${DATABASE_DEBUG} \
        NATIVE_LOGGER_TRACE=${NATIVE_LOGGER_TRACE} \
        DATABASE_USER=${DATABASE_USER} \
        DATABASE_PASSWORD=${DATABASE_PASSWORD} \
        DATABASE_HOST=${DATABASE_HOST} \
        DATABASE_PORT=${DATABASE_PORT} \
        DATABASE_NAME=${DATABASE_NAME} \
        DATABASE_MIGRATE=${DATABASE_MIGRATE} \
        BIRTHDAY_TITLE=${BIRTHDAY_TITLE} \
        BIRTHDAY_TEXT=${BIRTHDAY_TEXT} \
        NOTIFY_URL=${NOTIFY_URL} \
        NOTIFY_TOKEN=${NOTIFY_TOKEN}"

artifacts:
  files:
  - template.yaml
  - bin/**/*
  - .aws-sam/**/*
  discard-paths: no

cache:
  paths:
  - /go/pkg/mod/**/*
