version: "3.5"
services:
  axul_db_conctact:
    platform: linux/amd64
    container_name: axul_db_conctact
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: axul_contact
    ports:
      - "3320:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
