AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  axul-contact

  Sample SAM Template for axul-contact

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        NATIVE_LOGGER_TRACE: 15
        DATABASE_USER: "dunny"
        DATABASE_PASSWORD: "dunny"
        DATABASE_HOST: "dunny"
        DATABASE_PORT: "dunny"
        DATABASE_NAME: "dunny"
        DATABASE_MIGRATE: "false"
        DATABASE_DEBUG: "false"
        STAGE: dev
        BIRTHDAY_TITLE: "Cumpleaños de %s %s"
        BIRTHDAY_TEXT: "Mañana es el cumpleaños de %s, recorda saludarlo"
        NOTIFY_URL: "https://notify.axul.com.br/api/v1/push"
        NOTIFY_TOKEN: "1234567890"
  Api:
    TracingEnabled: true
Resources:
  ContactsGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/get
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: GET
  ContactsCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/create
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts
            Method: POST
  ContactsDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/delete
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: DELETE
  ContactsGetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/getall
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts
            Method: GET
  ContactsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/update
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: PATCH
  ContactsAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/contacts/alert
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /contacts/alert
            Method: POST
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  ContactsAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
